# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x08snapchat\"\xc0\x01\n\x14\x43onversationMetadata\x12\x35\n\x11\x63onversation_info\x18\x01 \x01(\x0b\x32\x1a.snapchat.ConversationInfo\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12+\n\x0cparticipants\x18\x03 \x03(\x0b\x32\x15.snapchat.Participant\x12\x30\n\x08settings\x18\x04 \x01(\x0b\x32\x1e.snapchat.ConversationSettings\"+\n\x10\x43onversationInfo\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\x0c\"|\n\x0bParticipant\x12\x0f\n\x07user_id\x18\x01 \x01(\x0c\x12\x17\n\x0funknown_field_2\x18\x02 \x01(\x03\x12\x17\n\x0funknown_field_3\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x17\n\x0funknown_field_9\x18\t \x01(\x03\"Y\n\x14\x43onversationSettings\x12\x15\n\rsettings_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x17\n\x0f\x61\x64\x64itional_data\x18\t \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONVERSATIONMETADATA._serialized_start=33
  _CONVERSATIONMETADATA._serialized_end=225
  _CONVERSATIONINFO._serialized_start=227
  _CONVERSATIONINFO._serialized_end=270
  _PARTICIPANT._serialized_start=272
  _PARTICIPANT._serialized_end=396
  _CONVERSATIONSETTINGS._serialized_start=398
  _CONVERSATIONSETTINGS._serialized_end=487
# @@protoc_insertion_point(module_scope)
