"""Initial migration - create all tables

Revision ID: c04ba21ff190
Revises: 
Create Date: 2025-09-09 20:58:16.899661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04ba21ff190'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ssh_host', sa.String(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(), nullable=False),
    sa.Column('ssh_key_path', sa.String(), nullable=True),
    sa.Column('android_version', sa.String(), nullable=True),
    sa.Column('snapchat_version', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extraction_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('messages_extracted', sa.Integer(), nullable=True),
    sa.Column('media_files_extracted', sa.Integer(), nullable=True),
    sa.Column('parsing_errors', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('extraction_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingest_runs_device_started', 'ingest_runs', ['device_id', 'started_at'], unique=False)
    op.create_index('idx_ingest_runs_status', 'ingest_runs', ['status'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('cache_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('timestamp_source', sa.String(), nullable=True),
    sa.Column('mapping_method', sa.String(), nullable=True),
    sa.Column('file_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_cache_id', 'media_assets', ['cache_id'], unique=False)
    op.create_index('idx_media_cache_key', 'media_assets', ['cache_key'], unique=False)
    op.create_index('idx_media_file_hash', 'media_assets', ['file_hash'], unique=False)
    op.create_index('idx_media_sender', 'media_assets', ['sender_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_message_id', sa.String(), nullable=True),
    sa.Column('client_message_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Integer(), nullable=False),
    sa.Column('cache_id', sa.String(), nullable=True),
    sa.Column('creation_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('read_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('parsing_successful', sa.Boolean(), nullable=True),
    sa.Column('raw_message_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_cache_id', 'messages', ['cache_id'], unique=False)
    op.create_index('idx_messages_conversation_timestamp', 'messages', ['conversation_id', 'creation_timestamp'], unique=False)
    op.create_index('idx_messages_sender_timestamp', 'messages', ['sender_id', 'creation_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_sender_timestamp', table_name='messages')
    op.drop_index('idx_messages_conversation_timestamp', table_name='messages')
    op.drop_index('idx_messages_cache_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_media_sender', table_name='media_assets')
    op.drop_index('idx_media_file_hash', table_name='media_assets')
    op.drop_index('idx_media_cache_key', table_name='media_assets')
    op.drop_index('idx_media_cache_id', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('idx_ingest_runs_status', table_name='ingest_runs')
    op.drop_index('idx_ingest_runs_device_started', table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_table('users')
    op.drop_table('devices')
    op.drop_table('conversations')
    # ### end Alembic commands ###
